name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:

      # 1. Скачать проект
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Java
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      # 4. Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 5. Установка зависимостей проекта
      - name: Install dependencies
        run: npm install

      # 6. Установка TypeScript
      - name: Install TypeScript
        run: npm install --save-dev typescript

      # 7. Проверка Capacitor
      - name: Check Capacitor
        run: npx cap --version

      # 8. Создание Android проекта
      - name: Add Android platform
        run: npx cap add android

      # 9. Синхронизация
      - name: Sync Capacitor
        run: npx cap sync android

      # 10. Сборка APK
      - name: Build Debug APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      # 11. Загрузка APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kadastr-Marshrut-v5-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
